png: support apng
artemsen/swayimg pull request #101
Opened 2023-12-22 17:37 UTC by appashchenko

Возможность просматривать анимированные PNG, если в системе пропатчена libpng.
Вторая попытка. 

Файлы для проверки
https://github.com/artemsen/swayimg/files/13753972/samples.tar.gz

2023-12-23 05:56 UTC, artemsen requested changes
Заранее извиняюсь, но я могу задержаться с этим PR.
Слишком много скользких моментов, проверять которые надо вручную, а у меня даже пропатченного libpng нет.

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
> +// APNG documentation
Необязательно в коде держать ссылки, это гуглится

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
> +static int decode_png_frame(struct image* ctx, png_structp png, png_infop info)
Возвращаемое значение или 0 или -1, можно заменить его на `bool`

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
> +    for (png_uint_32 i = 0; i < height; ++i) {
Я бы предпочёл стандартные типы вместо специфики PNG: `uint32_t` vs `png_uint_32`

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
> +static void delete_frames_keep_default(struct image* ctx, size_t last_frame)
Было бы не лишним добавить комментарий с описание функции.
Что она делает? Удаляет фреймы сохраняя что-то по умолчанию?

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
> +    // png_uint_32 num_plays;
Закомментаренный код не нужно коммитить.

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
> +static int decode_png_frames(struct image* ctx, png_structp png, png_infop info)
Тут тоже возврат `int`, но в коде только 0 или -1.

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
> +    buffer_size = width * height * 4;
Почему 4 а не 6?
Чтобы таких вопросов не возникало - не используйте магические константы. Можно заменить, например, на `sizeof(argb_t)`

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
> +    if (output_buffer == NULL) {
Это не ошибка, но синтаксический сахар. Указатели на NULL можно проверять просто `if (!output_buffer) {`

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
> +                                uint32_t u = fg_alpha * 255;
Макрос `ARGB_ALPHA_BLEND` не подойдёт для этого блока?

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
> +}
Это рекорд - самая большая функция во всём проекте! =)
Её очень сложно анализировать. Может разбить этот функционал на части?

2023-12-23 05:56 UTC, artemsen commented on src/formats/png.c
>  enum loader_status decode_png(struct image* ctx, const uint8_t* data,
Мне было бы проще, если вы сделаете отдельную реализацию загрузчика PNG.
Что-то типа такого:
```c
#ifdef PNG_APNG_SUPPORTED
// версия для пропатченного libpng
enum loader_status decode_png(...

#else 

// версия для ванильного libpng
enum loader_status decode_png(...

#endif
```

2023-12-26 14:59 UTC, appashchenko commented on src/formats/png.c
> +static int decode_png_frame(struct image* ctx, png_structp png, png_infop info)
Скорректировал

2023-12-26 15:07 UTC, appashchenko commented on src/formats/png.c
> +                                uint32_t u = fg_alpha * 255;
Подошёл. Нужно проверить, правильно ли я его использую.

2023-12-26 15:08 UTC, appashchenko commented on src/formats/png.c
> +}
Стала короче.

2023-12-26 15:50 UTC, appashchenko commented on src/formats/png.c
>  enum loader_status decode_png(struct image* ctx, const uint8_t* data,
Я в замешательстве: загрузчики совпадут на 90%, так как почти все действия общие.
Удаление из модифицированного загрузчика лишь нескольких строчек делает его ванильным, а 
ванильный загрузчик спокойно переварит анимированный файл, только покажет лишь первую картинку.

2023-12-27 14:55 UTC, appashchenko commented on src/formats/png.c
>  enum loader_status decode_png(struct image* ctx, const uint8_t* data,
Сделано

2023-12-27 14:57 UTC, merged

2023-12-27 14:57 UTC, artemsen commented
Спасибо!